const preguntasGrammar = [
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The bug has already ___ by the CI system.'", opciones: ["being fixed", "be fixed", "been fixed", "fixed"], respuesta: "been fixed" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The bug is currently ___ by the QA team.'", opciones: ["being fixed", "fix", "fixed", "been fixed"], respuesta: "being fixed" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'You must ___ the bug before deploying.'", opciones: ["fixed", "fix", "fixing", "fixes"], respuesta: "fix" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We finished ___ the bug.'", opciones: ["fixed", "fixing", "fix", "fixes"], respuesta: "fixing" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa (condicional cero): 'If tests fail, the pipeline ___ automatically.'", opciones: ["fixing", "fixed", "fixes", "fix"], respuesta: "fixes" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'If we had more time, we would ___ the bug more thoroughly.'", opciones: ["fixing", "fixed", "fix", "fixes"], respuesta: "fix" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'I used to ___ the bug manually before we had CI.'", opciones: ["fixed", "fixes", "fix", "fixing"], respuesta: "fix" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We are going to ___ the bug next week.'", opciones: ["fixes", "fix", "fixed", "fixing"], respuesta: "fix" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We added logging so that we could ___ the bug more easily.'", opciones: ["fixes", "fix", "fixing", "fixed"], respuesta: "fix" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'Keep ___ until it works.'", opciones: ["fixed", "fix", "fixing", "fixes"], respuesta: "fixing" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The module has already ___ by the CI system.'", opciones: ["being tested", "tested", "be tested", "been tested"], respuesta: "been tested" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The module is currently ___ by the QA team.'", opciones: ["test", "been tested", "tested", "being tested"], respuesta: "being tested" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'You must ___ the module before deploying.'", opciones: ["testing", "tests", "test", "tested"], respuesta: "test" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We finished ___ the module.'", opciones: ["test", "testing", "tested", "tests"], respuesta: "testing" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa (condicional cero): 'If tests fail, the pipeline ___ automatically.'", opciones: ["testing", "tested", "tests", "test"], respuesta: "tests" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'If we had more time, we would ___ the module more thoroughly.'", opciones: ["testing", "tests", "test", "tested"], respuesta: "test" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'I used to ___ the module manually before we had CI.'", opciones: ["tested", "testing", "tests", "test"], respuesta: "test" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We are going to ___ the module next week.'", opciones: ["testing", "tests", "tested", "test"], respuesta: "test" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We added logging so that we could ___ the module more easily.'", opciones: ["testing", "test", "tests", "tested"], respuesta: "test" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'Keep ___ until it works.'", opciones: ["test", "tested", "tests", "testing"], respuesta: "testing" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The application has already ___ by the CI system.'", opciones: ["be deployed", "being deployed", "been deployed", "deployed"], respuesta: "been deployed" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The application is currently ___ by the QA team.'", opciones: ["being deployed", "deployed", "deploy", "been deployed"], respuesta: "being deployed" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'You must ___ the application before deploying.'", opciones: ["deploy", "deploying", "deployed", "deploys"], respuesta: "deploy" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We finished ___ the application.'", opciones: ["deploys", "deploy", "deployed", "deploying"], respuesta: "deploying" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa (condicional cero): 'If tests fail, the pipeline ___ automatically.'", opciones: ["deploy", "deploying", "deployed", "deploys"], respuesta: "deploys" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'If we had more time, we would ___ the application more thoroughly.'", opciones: ["deployed", "deploying", "deploy", "deploys"], respuesta: "deploy" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'I used to ___ the application manually before we had CI.'", opciones: ["deploying", "deployed", "deploy", "deploys"], respuesta: "deploy" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We are going to ___ the application next week.'", opciones: ["deployed", "deploy", "deploys", "deploying"], respuesta: "deploy" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We added logging so that we could ___ the application more easily.'", opciones: ["deploy", "deployed", "deploys", "deploying"], respuesta: "deploy" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'Keep ___ until it works.'", opciones: ["deploying", "deploy", "deploys", "deployed"], respuesta: "deploying" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The package has already ___ by the CI system.'", opciones: ["be installed", "installed", "being installed", "been installed"], respuesta: "been installed" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The package is currently ___ by the QA team.'", opciones: ["install", "being installed", "installed", "been installed"], respuesta: "being installed" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'You must ___ the package before deploying.'", opciones: ["installing", "installs", "install", "installed"], respuesta: "install" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We finished ___ the package.'", opciones: ["installs", "installing", "install", "installed"], respuesta: "installing" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa (condicional cero): 'If tests fail, the pipeline ___ automatically.'", opciones: ["installed", "installs", "install", "installing"], respuesta: "installs" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'If we had more time, we would ___ the package more thoroughly.'", opciones: ["installing", "install", "installed", "installs"], respuesta: "install" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'I used to ___ the package manually before we had CI.'", opciones: ["installing", "installed", "installs", "install"], respuesta: "install" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We are going to ___ the package next week.'", opciones: ["installing", "installs", "installed", "install"], respuesta: "install" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We added logging so that we could ___ the package more easily.'", opciones: ["installed", "install", "installing", "installs"], respuesta: "install" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'Keep ___ until it works.'", opciones: ["installed", "installs", "installing", "install"], respuesta: "installing" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The dependency has already ___ by the CI system.'", opciones: ["updated", "being updated", "been updated", "be updated"], respuesta: "been updated" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The dependency is currently ___ by the QA team.'", opciones: ["been updated", "updated", "being updated", "update"], respuesta: "being updated" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'You must ___ the dependency before deploying.'", opciones: ["updates", "updating", "update", "updated"], respuesta: "update" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We finished ___ the dependency.'", opciones: ["update", "updated", "updating", "updates"], respuesta: "updating" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa (condicional cero): 'If tests fail, the pipeline ___ automatically.'", opciones: ["updating", "updates", "updated", "update"], respuesta: "updates" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'If we had more time, we would ___ the dependency more thoroughly.'", opciones: ["updated", "updating", "update", "updates"], respuesta: "update" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'I used to ___ the dependency manually before we had CI.'", opciones: ["updating", "updated", "updates", "update"], respuesta: "update" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We are going to ___ the dependency next week.'", opciones: ["update", "updated", "updating", "updates"], respuesta: "update" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We added logging so that we could ___ the dependency more easily.'", opciones: ["updates", "updated", "updating", "update"], respuesta: "update" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'Keep ___ until it works.'", opciones: ["updates", "update", "updating", "updated"], respuesta: "updating" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The pull request has already ___ by the CI system.'", opciones: ["being reviewed", "be reviewed", "been reviewed", "reviewed"], respuesta: "been reviewed" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The pull request is currently ___ by the QA team.'", opciones: ["been reviewed", "review", "being reviewed", "reviewed"], respuesta: "being reviewed" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'You must ___ the pull request before deploying.'", opciones: ["reviewed", "reviewing", "review", "reviews"], respuesta: "review" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We finished ___ the pull request.'", opciones: ["reviewing", "reviews", "reviewed", "review"], respuesta: "reviewing" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa (condicional cero): 'If tests fail, the pipeline ___ automatically.'", opciones: ["reviewed", "reviewing", "review", "reviews"], respuesta: "reviews" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'If we had more time, we would ___ the pull request more thoroughly.'", opciones: ["review", "reviewed", "reviewing", "reviews"], respuesta: "review" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'I used to ___ the pull request manually before we had CI.'", opciones: ["reviewed", "reviews", "review", "reviewing"], respuesta: "review" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We are going to ___ the pull request next week.'", opciones: ["review", "reviewed", "reviews", "reviewing"], respuesta: "review" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We added logging so that we could ___ the pull request more easily.'", opciones: ["reviewing", "review", "reviews", "reviewed"], respuesta: "review" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'Keep ___ until it works.'", opciones: ["reviewed", "reviews", "review", "reviewing"], respuesta: "reviewing" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The branch has already ___ by the CI system.'", opciones: ["be merged", "been merged", "merged", "being merged"], respuesta: "been merged" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The branch is currently ___ by the QA team.'", opciones: ["merge", "being merged", "been merged", "merged"], respuesta: "being merged" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'You must ___ the branch before deploying.'", opciones: ["merging", "merges", "merge", "merged"], respuesta: "merge" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We finished ___ the branch.'", opciones: ["merging", "merged", "merges", "merge"], respuesta: "merging" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa (condicional cero): 'If tests fail, the pipeline ___ automatically.'", opciones: ["merges", "merging", "merged", "merge"], respuesta: "merges" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'If we had more time, we would ___ the branch more thoroughly.'", opciones: ["merge", "merging", "merges", "merged"], respuesta: "merge" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'I used to ___ the branch manually before we had CI.'", opciones: ["merging", "merge", "merged", "merges"], respuesta: "merge" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We are going to ___ the branch next week.'", opciones: ["merging", "merges", "merge", "merged"], respuesta: "merge" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We added logging so that we could ___ the branch more easily.'", opciones: ["merging", "merged", "merges", "merge"], respuesta: "merge" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'Keep ___ until it works.'", opciones: ["merges", "merge", "merging", "merged"], respuesta: "merging" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The input has already ___ by the CI system.'", opciones: ["validated", "been validated", "being validated", "be validated"], respuesta: "been validated" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The input is currently ___ by the QA team.'", opciones: ["been validated", "validate", "validated", "being validated"], respuesta: "being validated" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'You must ___ the input before deploying.'", opciones: ["validating", "validates", "validate", "validated"], respuesta: "validate" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We finished ___ the input.'", opciones: ["validating", "validates", "validated", "validate"], respuesta: "validating" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa (condicional cero): 'If tests fail, the pipeline ___ automatically.'", opciones: ["validates", "validate", "validating", "validated"], respuesta: "validates" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'If we had more time, we would ___ the input more thoroughly.'", opciones: ["validate", "validating", "validates", "validated"], respuesta: "validate" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'I used to ___ the input manually before we had CI.'", opciones: ["validating", "validated", "validate", "validates"], respuesta: "validate" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We are going to ___ the input next week.'", opciones: ["validate", "validating", "validated", "validates"], respuesta: "validate" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We added logging so that we could ___ the input more easily.'", opciones: ["validated", "validate", "validating", "validates"], respuesta: "validate" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'Keep ___ until it works.'", opciones: ["validate", "validated", "validating", "validates"], respuesta: "validating" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The environment has already ___ by the CI system.'", opciones: ["being configured", "been configured", "configured", "be configured"], respuesta: "been configured" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The environment is currently ___ by the QA team.'", opciones: ["configured", "being configured", "configure", "been configured"], respuesta: "being configured" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'You must ___ the environment before deploying.'", opciones: ["configuring", "configures", "configured", "configure"], respuesta: "configure" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We finished ___ the environment.'", opciones: ["configures", "configuring", "configure", "configured"], respuesta: "configuring" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa (condicional cero): 'If tests fail, the pipeline ___ automatically.'", opciones: ["configure", "configures", "configuring", "configured"], respuesta: "configures" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'If we had more time, we would ___ the environment more thoroughly.'", opciones: ["configuring", "configures", "configured", "configure"], respuesta: "configure" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'I used to ___ the environment manually before we had CI.'", opciones: ["configures", "configured", "configuring", "configure"], respuesta: "configure" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We are going to ___ the environment next week.'", opciones: ["configured", "configure", "configuring", "configures"], respuesta: "configure" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We added logging so that we could ___ the environment more easily.'", opciones: ["configured", "configure", "configuring", "configures"], respuesta: "configure" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'Keep ___ until it works.'", opciones: ["configure", "configuring", "configures", "configured"], respuesta: "configuring" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The server has already ___ by the CI system.'", opciones: ["being restarted", "been restarted", "be restarted", "restarted"], respuesta: "been restarted" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'The server is currently ___ by the QA team.'", opciones: ["being restarted", "restart", "restarted", "been restarted"], respuesta: "being restarted" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'You must ___ the server before deploying.'", opciones: ["restarted", "restart", "restarting", "restarts"], respuesta: "restart" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We finished ___ the server.'", opciones: ["restart", "restarted", "restarts", "restarting"], respuesta: "restarting" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa (condicional cero): 'If tests fail, the pipeline ___ automatically.'", opciones: ["restart", "restarting", "restarted", "restarts"], respuesta: "restarts" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'If we had more time, we would ___ the server more thoroughly.'", opciones: ["restarted", "restart", "restarting", "restarts"], respuesta: "restart" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'I used to ___ the server manually before we had CI.'", opciones: ["restart", "restarted", "restarts", "restarting"], respuesta: "restart" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We are going to ___ the server next week.'", opciones: ["restart", "restarting", "restarted", "restarts"], respuesta: "restart" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'We added logging so that we could ___ the server more easily.'", opciones: ["restart", "restarted", "restarting", "restarts"], respuesta: "restart" },
  { categoria: "Gramática Avanzada Tech", pregunta: "Completa: 'Keep ___ until it works.'", opciones: ["restarting", "restart", "restarts", "restarted"], respuesta: "restarting" }
];
